resources:
  - name: vt1
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub
      branches:
        include: master
  - name: cron2
    type: CronTrigger
    configuration: 
      interval: "* */16 * * *"
 
pipelines:
  - name: pipeline_cron
    steps:          
      - name: bash_cron
        type: Bash
        configuration:
          inputResources:
            - name: vt1
            - name: cron2
        execution:
          onExecute:
            - echo "executing bash step......"
            - printenv
