resources:
  - name: github2
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub
      branches:
        include: master
 
pipelines:
  - name: pipeline_1
    steps:          
      - name: bash_1
        type: Bash
        configuration:
          inputResources:
            - name: github2
          integrations:
            - name: deepikaSlack
          runtime:            
            type: image
              custom:
                name: shippabledocker/jfreq
                tag: latest
                region: us-east-1
        execution:
          onExecute:
            - echo "executing bash step......"
            - printenv
            - pushd $res_github2_resourcePath
            - ls
            - source test.sh
            - echo $runId
            - popd

