pipelines:
  - name: pipeline_2
    steps:          
      - name: bash_2
        type: Bash
        configuration:
          inputResources:
            - name: github2
        execution:
          onExecute:
            - echo "executing bash step......"
