resources:
  - name: github_deep
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub
      branches:
        include: master
  - name: cron
    type: CronTrigger
    configuration: 
      interval: "*/2 * * * *"
 
pipelines:
  - name: pipeline_1
#     configuration:
#       runtime:            
#         type: image
#         image:
#           custom:
#             registry: aws
#             name: ubuntu
#             tag: latest
#             region: us-east-1
    steps:          
      - name: bash_1
        type: Bash
        configuration:
          inputResources:
            - name: github_deep
#             - name: cron
#           integrations:
#             - name: deepikaSlack
#             - name: deepikaAzure
        execution:
          onExecute:
            - echo "executing bash step......"
            - printenv
#             - az image list
#             - pushd $res_github2_resourcePath
#             - ls
#             - source test.sh
#             - echo $runId
#             - popd
