resources:
  - name: github
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub
  - name: myCronTrigger
    type: CronTrigger
    configuration:
      interval: "*/2 14 3 9 *"
 
pipelines:
  - name: pipeline
    steps:          
      - name: bash
        type: Bash
        configuration:
          inputResources:
            - name: github
            - name: myCronTrigger
        execution:
          onExecute:
            - echo "executing bash step..."
      - name: bash2
        type: Bash
        configuration:
          inputSteps:
            - name: bash
        execution:
          onExecute:
            - echo "executing bash2 step..."
  
