resources:
  - name: github2
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub
      branches:
        include: master
 
pipelines:
  - name: pipeline_1
#     configuration:
#       runtime:            
#         type: image
#         image:
#           custom:
#             registry: aws
#             name: ubuntu
#             tag: latest
#             region: us-east-1
    steps:          
      - name: bash_1
        type: Bash
        configuration:
          inputResources:
            - name: github2
#           integrations:
#             - name: deepikaSlack
#             - name: deepikaAzure
        execution:
          onExecute:
            - echo "executing bash stepab......"
            - printenv
            - echo "this branch is {{gitBranch}} "
            - echo "executing bash step..."
            - echo "state=$run_number" > pipeline_state.txt
            - add_pipeline_files pipeline_state.txt pipeline_state_file
            - echo "state=$run_number" > run_state.txt
            - add_run_files run_state.txt run_state_file
            - echo "state=$run_number" > cache.txt
            - restore_run_files run_state_file run_state.txt
            - restore_cache_files pipeline_state_cache cache.txt
            - add_cache_files cache.txt pipeline_state_cache
#             - az image list
#             - pushd $res_github2_resourcePath
#             - ls
#             - source test.sh
#             - echo $runId
#             - popd

