resources:
  - name: github2
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: deepikaGithub
 
pipelines:
  - name: pipeline_1
    steps:          
      - name: bash_1
        type: Bash
        configuration:
          inputResources:
            - name: github2
        execution:
          onExecute:
            - echo "executing bash step......"

