resources:
  - name: github2
    type: GitRepo
    configuration:
      path: deepikasl/VT1
      gitProvider: github
      branches:
        include: master
  - name: github3
    type: GitRepo
    configuration:
      path: deepikasl/VT2
      gitProvider: deepikaGithub
      branches:
        include: master
  - name: github4
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: test
      branches:
        include: master
  - name: github19
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: github
      branches:
        include: master
  - name: github20
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: github
      branches:
        include: master
  - name: github7
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: github
      branches:
        include: master
  - name: github8
    type: GitRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master1
  - name: github9
    type: GitRepo
    configuration:
      path: deepikasl/sample_node
      gitProvider: github
      branches:
        include: master
#   - name: github11
#     type: GitRepo
#     configuration:
#       path: deepikasl/jfrog_pipelines
#       gitProvider: test
#       branches:
#         include: master1
  - name: github12
    type: GitRepo
    configuration:
      path: deepikasl/sample_node
      gitProvider: test
      branches:
        include: master13
  - name: go_build_info_publish_gb8
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: go_example_build_publish
      buildNumber: 11
pipelines:
  - name: pipeline_1
#     configuration:
#       runtime:            
#         type: image
#         image:
#           custom:
#             registry: aws
#             name: ubuntu
#             tag: latest
#             region: us-east-1
    steps:          
      - name: bash_1
        type: Bash
        configuration:
          inputResources:
            - name: github2
            - name: github3
            - name: github4
            - name: github9
#             - name: github7
#             - name: github8
            - name: go_build_info_publish_gb8
#           integrations:
#             - name: deepikaSlack
#             - name: deepikaAzure
        execution:
          onExecute:
            - echo "executing bash stepabcd......"
            - printenv
#             - az image list
#             - pushd $res_github2_resourcePath
#             - ls
#             - source test.sh
#             - echo $runId
#             - popd

